language: ruby
rvm:
   - "2.2.0"
#  - "1.8.7"
#  - "1.9.2"
#  - "1.9.3"
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database legislative_twitter_test;' -U postgres